import type { Chapter, Term, Question, Source, Domain } from '../types';

const urls = {
 regions:'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html',
 responsibility:'https://aws.amazon.com/compliance/shared-responsibility-model/',
 iam:'https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html',
 policy:'https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_evaluation-logic.html',
 role:'https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html',
 external:'https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_third-party.html',
 scp:'https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps.html',
 route:'https://docs.aws.amazon.com/vpc/latest/userguide/subnet-route-tables.html',
 sg:'https://docs.aws.amazon.com/vpc/latest/userguide/vpc-security-groups.html',
 acl:'https://docs.aws.amazon.com/vpc/latest/userguide/vpc-network-acls.html',
 nat:'https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html',
 endpoint:'https://docs.aws.amazon.com/vpc/latest/privatelink/gateway-endpoints.html',
 peering:'https://docs.aws.amazon.com/vpc/latest/peering/what-is-vpc-peering.html',
 tgw:'https://docs.aws.amazon.com/vpc/latest/tgw/what-is-transit-gateway.html',
 vpn:'https://docs.aws.amazon.com/vpn/latest/s2svpn/VPC_VPN.html',
 ec2:'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-purchasing-options.html',
 alb:'https://docs.aws.amazon.com/elasticloadbalancing/latest/application/introduction.html',
 nlb:'https://docs.aws.amazon.com/elasticloadbalancing/latest/network/introduction.html',
 asg:'https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-scaling-target-tracking.html',
 store:'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/InstanceStorage.html',
 s3:'https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html',
 classes:'https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage-class-intro.html',
 version:'https://docs.aws.amazon.com/AmazonS3/latest/userguide/Versioning.html',
 lock:'https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html',
 signed:'https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-presigned-url.html',
 replication:'https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication.html',
 ebs:'https://docs.aws.amazon.com/ebs/latest/userguide/ebs-volume-types.html',
 efs:'https://docs.aws.amazon.com/efs/latest/ug/features.html',
 multi:'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.MultiAZSingleStandby.html',
 replica:'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ReadRepl.html',
 dynamo:'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.ReadConsistency.html',
 key:'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-partition-key-design.html',
 index:'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/SecondaryIndexes.html',
 backup:'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithAutomatedBackups.html',
 proxy:'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy.html',
 cache:'https://docs.aws.amazon.com/AmazonElastiCache/latest/dg/WhatIs.html',
 kms:'https://docs.aws.amazon.com/kms/latest/developerguide/overview.html',
 secret:'https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotating-secrets.html',
 waf:'https://docs.aws.amazon.com/waf/latest/developerguide/what-is-aws-waf.html',
 cloudtrail:'https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-user-guide.html',
 config:'https://docs.aws.amazon.com/config/latest/developerguide/WhatIsConfig.html',
 cloudfront:'https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Introduction.html',
 route53:'https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy.html',
 sqs:'https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/welcome.html',
 sns:'https://docs.aws.amazon.com/sns/latest/dg/welcome.html',
 lambda:'https://docs.aws.amazon.com/lambda/latest/dg/welcome.html',
 fargate:'https://docs.aws.amazon.com/AmazonECS/latest/developerguide/AWS_Fargate.html',
 athena:'https://docs.aws.amazon.com/athena/latest/ug/what-is.html',
 dms:'https://docs.aws.amazon.com/dms/latest/userguide/Welcome.html',
 dr:'https://docs.aws.amazon.com/whitepapers/latest/disaster-recovery-workloads-on-aws/disaster-recovery-options-in-the-cloud.html',
 savings:'https://docs.aws.amazon.com/savingsplans/latest/userguide/what-is-savings-plans.html',
 budgets:'https://docs.aws.amazon.com/cost-management/latest/userguide/budgets-managing-costs.html',
 ssm:'https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager.html',
 cognito:'https://docs.aws.amazon.com/cognito/latest/developerguide/what-is-amazon-cognito.html',
 glacier:'https://docs.aws.amazon.com/AmazonS3/latest/userguide/restoring-objects.html',
 direct:'https://docs.aws.amazon.com/directconnect/latest/UserGuide/Welcome.html',
 datasync:'https://docs.aws.amazon.com/datasync/latest/userguide/what-is-datasync.html',
 fsx:'https://docs.aws.amazon.com/fsx/latest/WindowsGuide/what-is.html',
 aurora:'https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Concepts.AuroraHighAvailability.html',
 global:'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GlobalTables.html',
 lifecycle:'https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lifecycle-mgmt.html',
 multipart:'https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html',
 s3encrypt:'https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingServerSideEncryption.html',
 privatelink:'https://docs.aws.amazon.com/vpc/latest/privatelink/what-is-privatelink.html',
 transfer:'https://docs.aws.amazon.com/AmazonS3/latest/userguide/transfer-acceleration.html',
 snapshot:'https://docs.aws.amazon.com/ebs/latest/userguide/ebs-snapshots.html',
 eventbridge:'https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-what-is.html',
 step:'https://docs.aws.amazon.com/step-functions/latest/dg/welcome.html',
 shield:'https://docs.aws.amazon.com/waf/latest/developerguide/shield-chapter.html',
 macie:'https://docs.aws.amazon.com/macie/latest/user/what-is-macie.html',
 guard:'https://docs.aws.amazon.com/guardduty/latest/ug/what-is-guardduty.html',
 inspector:'https://docs.aws.amazon.com/inspector/latest/user/what-is-inspector.html',
 access:'https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html',
 cloudwatch:'https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/WhatIsCloudWatch.html',
 redshift:'https://docs.aws.amazon.com/redshift/latest/mgmt/welcome.html',
 kinesis:'https://docs.aws.amazon.com/streams/latest/dev/introduction.html',
 glue:'https://docs.aws.amazon.com/glue/latest/dg/what-is-glue.html',
 gateway:'https://docs.aws.amazon.com/storagegateway/latest/userguide/WhatIsStorageGateway.html',
 placement:'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/placement-groups.html',
 cognitoid:'https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-identity.html',
 identity:'https://docs.aws.amazon.com/singlesignon/latest/userguide/what-is.html',
 sts:'https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp.html',
 boundary:'https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html',
 abac:'https://docs.aws.amazon.com/IAM/latest/UserGuide/introduction_attribute-based-access-control.html',
 s3block:'https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html',
 egress:'https://docs.aws.amazon.com/vpc/latest/userguide/egress-only-internet-gateway.html',
 flow:'https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html',
 scaling:'https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-scheduled-scaling.html',
 health:'https://docs.aws.amazon.com/autoscaling/ec2/userguide/health-checks-overview.html',
 warm:'https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-warm-pools.html',
 ami:'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html',
 spot:'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-spot-instances.html',
 capacity:'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-capacity-reservations.html',
 ttl:'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TTL.html',
 ondemand:'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/on-demand-capacity-mode.html',
 dax:'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAX.html',
 transactions:'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/transactions.html',
 s3consistency:'https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html#ConsistencyModel',
 s3iam:'https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-policy-language-overview.html'
} satisfies Record<string,string>;
type Key=keyof typeof urls;
const source=(key:Key):Source=>({title:`AWS公式: ${key}`,url:urls[key],checked:'2026-10-05'});
const lesson=(ch:number,n:number,title:string,analogy:string,explanation:string,diagram:string[],points:string[],comparison: [string,string,string][],conceptIds:string[],keys:Key[])=>({id:`ch${String(ch).padStart(2,'0')}-l${String(n).padStart(2,'0')}`,title,analogy,explanation,diagram,points,comparison:comparison.map(([name,use,caution])=>({name,use,caution})),conceptIds,sources:keys.map(source)});
export const chapters1:Chapter[]=[
 {id:'ch01',title:'AWSの全体像',intro:'サービス名より先に、置き場所・責任・障害の範囲を理解します。',lessons:[
 lesson(1,1,'リージョンとAZ','リージョンを都市、AZを別々の電源を持つ拠点として考えます。','リージョンは地理的な区分、AZはリージョン内の独立した場所です。EC2を同じAZに増やしても、そのAZ全体の障害には弱いままです。複数AZへの配置とリクエストの切り替えを組み合わせて可用性を設計します。リージョン選定では利用者との距離、データ保管要件、サービス提供状況も確認します。',['リージョン','├ AZ-A → EC2-A','└ AZ-B → EC2-B'],['AZ分散とリージョン分散は障害範囲が異なる。','リソースは原則として他リージョンへ自動複製されない。','確認：同じAZでサーバーを2台にするとAZ障害を防げる？ → 防げない。'],[['Multi-AZ','AZ障害への備え','アプリとデータ両方の冗長化が必要'],['Multi-Region','リージョン障害への備え','複製と切り替えの設計が増える']],['region','az'],['regions']),
 lesson(1,2,'責任共有モデル','建物の管理者が設備を守っても、部屋の鍵と中の書類は利用者が管理します。','AWSは物理施設やクラウド基盤を守ります。EC2のゲストOSの更新、アプリケーション、権限設定は利用者側です。S3のようなマネージドサービスでも、データ分類とアクセス権の責任は残ります。責任の境界は利用するサービスによって変わるため、「AWSに置けばすべて安全」と判断しないことが大切です。',['AWS → 施設・物理ホスト・基盤','利用者 → データ・権限・アプリ','EC2利用者 → ゲストOSも管理'],['管理作業が減っても利用者の責任がなくなるわけではない。','確認：S3のデータを誰に公開するか決めるのは？ → 利用者。'],[['EC2','OSまで自由に構成','OSの保守が必要'],['マネージドDB','保守の一部をAWSへ任せる','データと権限は利用者が管理']],['shared-responsibility'],['responsibility']),
 lesson(1,3,'要件から構成を選ぶ','車を選ぶとき、最高速度だけでなく人数・安全性・予算を比較するのと同じです。','SAAの問題では、障害に耐える範囲、応答時間、管理負荷、費用を分けて読みます。「最小コスト」でも停止できない処理に中断される実行基盤を選ぶことはできません。まず必須条件を満たす候補を残し、その中で費用や運用負荷を比較します。処理台数を増やす設計では、セッションを1台だけに閉じ込めない工夫も必要です。',['要件 → 必須条件を抽出','→ 不適合な候補を除外','→ コスト・運用で比較'],['可用性は動き続ける性質、耐久性はデータを失いにくい性質。','複製だけでは誤削除から戻せるとは限らない。','確認：停止不可の唯一のサーバーをSpotだけで構成してよい？ → 中断への備えが必要。'],[['スケールアップ','1台を大きくする','1台への依存が残る'],['スケールアウト','複数台に処理を分ける','状態と負荷分散を設計する']],['availability','scaling'],['regions','ec2'])]},
 {id:'ch02',title:'IAMとアクセス制御',intro:'誰が、何に、何をできるかを最小限に定めます。',lessons:[
 lesson(2,1,'ユーザー・ロール・一時認証情報','社員証を共有する代わりに、作業中だけ有効な入館証を渡すイメージです。','IAMロールはサービスや人が引き受ける権限の器です。EC2上のアプリにアクセスキーを埋め込む代わりに、必要なS3操作だけ許可したロールを利用します。人のアクセスではフェデレーションやIAM Identity Centerを使い、一時認証情報とMFAを基本にします。ルートユーザーは日常作業に使いません。',['人・EC2 → ロールを引き受ける','→ 有効期限付き認証情報','→ 許可されたAWS操作'],['ロールの信頼ポリシーは誰が引き受けられるかを決める。','権限ポリシーは引き受けた後の操作を決める。','確認：EC2のソースコードに固定キーを保存する？ → インスタンスロールを使う。'],[['IAMユーザー','必要時に長期IDを管理','長期キー管理の負担'],['IAMロール','一時的なサービス・人の権限','信頼関係と権限の両方を設定']],['iam-role','temporary-credentials'],['iam','role','sts']),
 lesson(2,2,'Allow・Denyと最小権限','許可証があっても、立入禁止の部屋には入れません。','IAMでは明示的なDenyがAllowより優先します。許可がない場合も原則拒否されます。Action、Resource、Conditionを絞り、必要な操作だけを与えます。SCPやアクセス許可の境界は付与可能な権限の上限であり、それだけで操作を許可しません。ポリシー評価にはリソースポリシーやセッション種別による違いがあるため、単純な足し算だけで判断しないようにします。',['要求 → 明示的Denyあり？ → 拒否','→ 許可と各種制約を確認','→ 条件を満たした操作だけ許可'],['S3バケット自体とオブジェクトはResourceの指定が異なる。','ワイルドカードは必要性を確認する。','確認：SCPでAllowしただけでEC2を起動できる？ → IAM側の許可等も必要。'],[['権限ポリシー','具体的な操作を許可','明示的Denyを上書きできない'],['SCP','組織の上限を設定','単体では権限を付与しない']],['least-privilege','explicit-deny','scp'],['policy','scp','boundary']),
 lesson(2,3,'アカウントをまたぐ安全な委任','別会社へ合鍵を渡す代わりに、対象と期限が決まった受付手続きを設けます。','別アカウントの担当者にはクロスアカウントロールを用意します。信頼ポリシーと呼び出し側の権限を整え、外部業者が複数顧客を扱う場合はExternal IDで混乱した代理問題に備えます。人のログインをまとめるIAM Identity Centerと、アプリ利用者の認証を扱うCognitoは用途が異なります。権限は継続的に見直し、不要なアクセスを減らします。',['利用元アカウント → STS AssumeRole','→ 利用先の信頼ポリシーを評価','→ 対象ロールの権限で操作'],['アクセスキーの共有で委任しない。','External IDはパスワードではなく顧客の取り違えを防ぐ条件。','確認：取引先へ自社ルートキーを渡す？ → 限定ロールで委任する。'],[['Identity Center','従業員のAWSアクセス','一般消費者向け会員基盤とは別'],['Cognito','アプリ利用者の認証','AWS管理者用統合アクセスとは別']],['cross-account','external-id','identity-center'],['external','identity','cognito'])]},
 {id:'ch03',title:'VPCとネットワーク',intro:'通信経路と通信許可を分けて考え、公開範囲を小さくします。',lessons:[
 lesson(3,1,'サブネットとルート','住所区画がサブネット、道案内の標識がルートテーブルです。','VPCはリージョン内の論理ネットワークです。サブネットは1つのAZに属し、ルートテーブルで宛先への経路を決めます。IPv4のインターネット公開にはIGWへの経路だけでなく、パブリックIPと通信許可も必要です。プライベートサブネットから外部へ出る場合はNATなどを使い、外からの新規接続を許可しない構成にできます。',['Internet ↔ IGW ↔ 公開サブネット','非公開サブネット → NAT → IGW','サブネット → ルートテーブルを参照'],['経路があってもSGで拒否されれば届かない。','最も具体的な一致する宛先プレフィックスを優先する。','確認：IGWへの経路だけでプライベートIPのみのEC2を公開できる？ → できない。'],[['公開サブネット','IGWへの直接経路','全EC2が自動公開されるわけではない'],['非公開サブネット','外部から直接接続させない層','外向き通信も別途経路が必要']],['vpc','subnet','route'],['route','nat']),
 lesson(3,2,'SGとネットワークACL','SGは部屋の入館許可、ACLは区画の検問と考えます。','セキュリティグループは許可ルールを持ち、許可された通信の戻りを追跡するステートフルな仕組みです。ネットワークACLはサブネット単位で許可と拒否を設定でき、状態を追跡しないため戻り方向も検討します。ALBからアプリ、アプリからDBという許可は、可能なら送信元SGで結び、変動する個々のIPへの依存を減らします。',['ALBのSG → アプリSGの受信許可','アプリSG → DBのSGの受信許可','サブネット境界 → ACL'],['SGは明示的拒否ルールを持たない。','ACLはルール番号順に評価する。','確認：ACLの受信だけ許可すれば戻り通信は自動許可？ → 送信も必要。'],[['SG','リソースの通信許可','拒否の個別ルールは作れない'],['ACL','サブネットで許可・拒否','戻りポートも考慮']],['security-group','network-acl'],['sg','acl']),
 lesson(3,3,'閉域接続と外部接続','公道へ出ず施設内の通路を使うのがVPCエンドポイントです。','S3とDynamoDBへのゲートウェイエンドポイントはルートテーブル経由でアクセスし、NATを不要にできます。PrivateLinkのインターフェイスエンドポイントはプライベートIPのネットワークインターフェイスを利用します。VPCピアリングは2つのVPCを直接接続し、経由転送はしません。多拠点接続にはTransit Gateway、オンプレミスとの暗号化トンネルにはSite-to-Site VPNなどを検討します。',['非公開EC2 → Gateway endpoint → S3','VPC-A ↔ Transit Gateway ↔ VPC-B','拠点 → VPN → AWS'],['接続方式とIAM権限は別々に満たす。','重複CIDRはVPC間接続の制約になる。','確認：A-BとB-CをピアリングすればA-Cも通る？ → 推移的ルーティングはない。'],[['Gateway endpoint','S3・DynamoDBへの経路','他サービスには使えない'],['Interface endpoint','対応サービスへのPrivateLink','時間・処理量等の費用を考慮']],['vpc-endpoint','peering','transit-gateway'],['endpoint','privatelink','peering','tgw','vpn'])]},
 {id:'ch04',title:'EC2・負荷分散・Auto Scaling',intro:'計算能力を必要なだけ用意し、障害時にも処理を引き継ぎます。',lessons:[
 lesson(4,1,'EC2の実行方式と購入方式','必要な席を都度借りるか、長期利用を約束するか、空席を安く使うかの違いです。','EC2は仮想サーバーです。予測できない短期利用はオンデマンド、安定した使用量にはSavings Plans等、中断されても再実行できる処理にはSpotを検討します。価格割引とキャパシティ確保は別の要件です。インスタンスストアのデータは停止・終了などで失われるため、永続データの唯一の保存先にしません。',['AMI → EC2起動','実行 → 外部永続ストレージへ保存','中断可能な処理 → Spotを検討'],['OS選択やインスタンス種類はCPU・メモリ・I/Oの要件で決める。','確認：料金割引だけで希望AZの起動容量が保証される？ → 別途容量要件を確認する。'],[['オンデマンド','短期・不定期','長期の一定利用では割引を比較'],['Spot','再実行できるバッチ','中断に耐える設計が必要']],['ec2','spot','savings-plans'],['ec2','store','capacity']),
 lesson(4,2,'ALBとNLB','受付がURLを見て窓口へ振り分けるのがALB、通信接続を配るのがNLBです。','ALBはHTTP/HTTPSのリクエストを扱い、ホスト名やパスに応じてターゲットグループへ振り分けます。NLBはTCP/UDP/TLSなどのトラフィックを扱い、固定IPが必要な場合にも候補です。負荷分散装置だけでアプリが冗長化されるわけではなく、複数AZの正常なターゲットと適切なヘルスチェックを用意します。',['利用者 → ALB','/api → APIターゲットグループ','/images → 画像ターゲットグループ'],['HTTPS終端の場所と証明書管理を決める。','確認：HTTPパスで振り分けたいなら？ → ALB。'],[['ALB','HTTPの内容に応じたルーティング','任意のUDPは扱わない'],['NLB','TCP・UDPと固定IP要件','URLパスで判定する用途ではない']],['alb','nlb','health-check'],['alb','nlb']),
 lesson(4,3,'台数調整と状態の分離','混雑した店でレジを増やしても、会計情報を1台だけに置くと交代できません。','Auto Scalingグループは希望台数を維持し、ポリシーに応じてEC2を増減します。ターゲット追跡では平均CPU使用率等の目標を設定します。朝の混雑時刻が既知ならスケジュールで先に増やす方法もあります。縮退時に処理やセッションを失わないよう、状態を外部ストアへ分離し、起動時間とウォームアップを考慮します。',['指標 → スケーリング判断 → 台数変更','ALB → EC2-A / EC2-B','各EC2 → 共通データ保存先'],['最小・最大・希望台数を区別する。','アプリ異常を検知させるにはELBヘルスチェック連携も検討。','確認：ASG追加だけでローカルのセッションが共有される？ → されない。'],[['ターゲット追跡','指標の目標値を維持','増台までの遅延がある'],['スケジュール','予測できる混雑に備える','突発的な変化は別対策']],['auto-scaling','stateless'],['asg','scaling','health'])]},
 {id:'ch05',title:'ストレージを選ぶ',intro:'保存形式、共有方法、復旧時間でS3・EBS・EFSを使い分けます。',lessons:[
 lesson(5,1,'オブジェクト・ブロック・ファイル','荷物を番号で預ける倉庫がS3、サーバー用ディスクがEBS、共有フォルダがEFSです。','S3はバケット内のキーでオブジェクトを扱い、画像やログの大量保存に向きます。EBSはEC2に接続するブロックストレージで、通常は同じAZで利用します。EFSはLinux等からNFSで共有できるファイルストレージです。既存アプリが要求するアクセス方式を確かめて選びます。S3をそのままPOSIXファイルシステムとみなしてはいけません。',['Web → S3（オブジェクト）','EC2 → EBS（ブロック）','EC2-A / EC2-B → EFS（共有ファイル）'],['WindowsのSMB要件ではFSx for Windows File Server等を比較。','確認：複数AZのLinuxで同じファイルを共有するなら？ → Regional EFS。'],[['S3','APIで画像・ログ保存','一般的なOSディスクではない'],['EBS','EC2のOS・DBディスク','AZ境界に注意'],['EFS','NFS共有','アクセス方式と性能を確認']],['s3','ebs','efs'],['s3','ebs','efs','fsx']),
 lesson(5,2,'保存期間とアクセス頻度','毎日使う書類は机、ほとんど使わない書類は保管庫へ移します。','S3のストレージクラスはアクセス頻度、取得待ち時間、AZ障害への耐性で選びます。頻度が変わり予測困難ならIntelligent-Tieringが候補です。Glacier Flexible RetrievalやDeep Archiveでは即時アクセスを前提にせず、復元時間を要件と比較します。Lifecycleで移行と期限切れ処理を自動化できますが、最低保存期間やリクエスト・取り出し費用も考慮します。',['作成 → S3 Standard','経過日数 → Lifecycle移行','長期保管 → アーカイブ → 復元'],['One Zone系は再作成できない唯一のデータの保護要件を確認。','確認：即時取得必須のデータをDeep Archiveに置く？ → 復元待ちが不適合。'],[['Standard-IA','低頻度でも即時取得','取り出し料金と最低保存期間'],['Deep Archive','長期・まれな復元','復元に時間がかかる']],['storage-class','lifecycle'],['classes','lifecycle','glacier']),
 lesson(5,3,'誤削除・不正アクセス・災害に備える','コピー、変更履歴、開けられない封印はそれぞれ別の防御です。','Versioningは上書きや通常の削除から戻すための旧版を保存します。Object Lockは特定のバージョンを保持期間などで保護します。別リージョンへの複製は災害対策に役立ちますが、複製だけで全ての誤操作を防ぐわけではありません。限定公開には短い有効期限の署名付きURLを使い、常時公開を避けられます。暗号化しても権限設定を省略できません。',['PUT → 新バージョン','旧バージョン → 保持・必要なら復旧','署名付きURL → 期限内の限定アクセス'],['Object Lockはバージョン単位で保護する。','署名付きURLの有効期間は元の認証情報の期限にも制約される。','確認：暗号化だけで匿名アクセスを防げる？ → 権限制御が別途必要。'],[['Versioning','旧版から復旧','旧版の保存費用が発生'],['Object Lock','保持中のバージョン保護','モードと保持条件の理解が必要']],['versioning','object-lock','presigned-url'],['version','lock','replication','signed'])]},
 {id:'ch06',title:'データベースとキャッシュ',intro:'整合性・可用性・アクセスパターンからデータの置き方を決めます。',lessons:[
 lesson(6,1,'RDSの可用性と読み取り拡張','非常時の代役と、普段から客を分担する係は役割が違います。','RDSのMulti-AZ DBインスタンス配置は、別AZのスタンバイへ同期複製し、障害時の切り替えに備えます。このスタンバイは読み取り処理に使いません。一方リードレプリカは読み取り負荷の分散に使いますが、複製遅延を考慮します。Multi-AZ DBクラスターの読み取り可能なスタンバイとは区別して問題文を読みます。',['書き込み → プライマリ → 同期 → スタンバイ','読み取り拡張 → 非同期レプリカ','障害 → 切り替え → 接続再試行'],['Multi-AZにしてもアプリの再接続処理は必要。','確認：DBインスタンス配置のスタンバイへ分析SQLを流せる？ → できない。'],[['Multi-AZ DBインスタンス','高可用性','スタンバイで読み取り不可'],['リードレプリカ','参照処理を分散','遅延したデータを読む可能性']],['rds-multi-az','read-replica'],['multi','replica']),
 lesson(6,2,'DynamoDBのキーと整合性','図書館で目的の棚に直行するか、全棚を探すかで作業量が変わります。','DynamoDBはキーに基づくアクセスに向くマネージドNoSQLデータベースです。パーティションキーの偏りは負荷集中を招きます。必要な問い合わせを先に考え、別のキーで検索したい場合はGSI等を設計します。テーブルとLSIでは強い整合性の読み取りを選べますが、GSIは結果整合性です。Scanを多用する前にキー設計を見直します。',['要求 → パーティションキーで分散','テーブル → 別キーのGSI','読み取り → 整合性要件を選択'],['読み取り直後の最新値が必要かを確認する。','確認：GSIで強い整合性を指定できる？ → できない。'],[['Query','キー条件で効率的に取得','キーに沿う設計が必要'],['Scan','広く項目を読み取る','大量データではコストと遅延に注意']],['dynamodb','partition-key','gsi','consistency'],['dynamo','key','index']),
 lesson(6,3,'復元・接続・キャッシュ','予備の帳簿、受付の整理係、よく使う情報のメモは別々に役立ちます。','RDSの自動バックアップは保持期間内の時点復元に役立ち、誤更新前の状態を別DBとして復元できます。RDS Proxyは接続をプールし、短時間に多数の接続を作るアプリの負担を和らげます。ElastiCacheやDAXは繰り返す読み取りを高速化しますが、元データ更新後の失効や整合性を設計する必要があります。バックアップは取得だけでなく復元手順も確認します。',['アプリ → Proxy → RDS','アプリ → キャッシュ → ミス時にDB','バックアップ → 別DBへ復元'],['キャッシュは障害対策用バックアップの代わりではない。','確認：接続数急増にはDBの読み取りレプリカ追加だけで十分？ → 接続プールも検討。'],[['RDS Proxy','接続の再利用','SQL結果キャッシュではない'],['ElastiCache','頻繁な読み取りを高速化','失効と整合性を設計']],['rds-proxy','cache','point-in-time-recovery'],['backup','proxy','cache','dax'])]}
];
export const terms1:Term[]=chapters1.flatMap(ch=>ch.lessons.flatMap(l=>l.comparison.map((c,i)=>({id:`${l.id}-term${i+1}`,name:c.name,meaning:`${c.use}。注意：${c.caution}。`,chapterId:ch.id}))));

// 行ごとに作問した選択肢と解説を保持。正答位置はIDから決定的に回転し、暗記を防ぐ。
function q(id:string,ch:number,domain:Domain,key:Key,concept:string,prompt:string,choices:string[],correct:number[]= [0],exam?:'mock1'):Question {
 const offset=Number(id.replace(/\D/g,''))%choices.length;
 const options=choices.map((_,i)=>{const raw=choices[(i+offset)%choices.length];const p=raw.indexOf('~');return {id:String.fromCharCode(97+i),text:raw.slice(0,p),explanation:raw.slice(p+1)};});
 const answers=correct.map(i=>String.fromCharCode(97+(i-offset+choices.length)%choices.length));
 return {id,chapterId:`ch${String(ch).padStart(2,'0')}`,domain,conceptIds:[concept],prompt,options,answers,explanation:correct.map(i=>choices[i].split('~')[1]).join(' '),sources:[source(key)],...(exam?{exam}:{})};
}
export const questions1:Question[]=[
q('q001',1,2,'regions','az','同じAZにEC2を2台置いた予約サイトがAZ障害で停止した。再発時にも稼働させる改善は？',['別AZにもEC2を配置し負荷分散する~障害範囲を分け、残ったAZへ処理を引き継げる。','同じAZに1台追加する~台数を増やしてもAZ全体の障害を共有する。','全台のCPUを増やす~処理能力を増やしても場所の障害には対処できない。','ルートボリュームだけ拡張する~容量追加はサービス継続経路を作らない。']),
q('q002',1,1,'responsibility','shared-responsibility','EC2上のWebアプリでゲストOSの脆弱性が見つかった。修正を計画する主体は？',['利用者~EC2ゲストOSとアプリの保守は利用者の責任。','AWSの施設管理担当~物理施設の保守とゲストOS更新は別の責任範囲。','ドメイン登録事業者~DNSの管理者はEC2のOSを保守しない。','自動的にAWSが全件修正する~EC2のゲストOS更新を無条件に代行するわけではない。']),
q('q003',1,1,'responsibility','shared-responsibility','S3に機密ファイルを保存する。利用者が引き続き管理すべき項目は？',['誰に読み取りを許可するか~マネージド保存でもデータへのアクセス権は利用者が設定する。','ストレージ装置の物理交換~物理インフラはAWSの管理範囲。','データセンターの入館警備~AWS施設の物理的保護はAWSが担う。','S3基盤OSのパッチ作業~S3の基盤OSは利用者が直接管理しない。']),
q('q004',1,2,'regions','region','大阪のEC2が東京リージョンのコンソールに表示されない。最初に確認することは？',['表示リージョンを大阪に切り替える~EC2リソースはリージョン単位で表示される。','EC2を再作成する~表示範囲の問題を解く前に再作成する必要はない。','S3の公開設定を変更する~EC2のリージョン表示とは無関係。','ルートアカウントのパスワードを変更する~表示先リージョンの違いは解消しない。']),
q('q005',1,3,'regions','region','日本の利用者向けサービスで往復通信時間を短くしたい。リージョン選定で優先して評価する項目は？',['利用者からの距離と実測遅延~近いリージョンを候補に、必要機能と測定結果を合わせて選ぶ。','リージョン名の文字数~ネットワーク遅延に影響しない。','アカウント作成者の住所だけ~実際の利用者との通信経路が重要。','AZ名が全アカウントで同じ物理場所か~利用者との地理的距離の評価にはならない。']),
q('q006',1,2,'regions','region','単一リージョン全体が使えない場合にも業務を継続したい。追加すべき設計範囲は？',['別リージョンへのデータ複製と切り替え~リージョン障害の外側に復旧先を用意する。','同一AZ内のインスタンス増設~リージョン全体の障害に巻き込まれる。','同一リージョン内のAZ追加だけ~AZ障害には有効でもリージョン障害の要件を満たさない。','CPUアラームの閾値だけ変更~復旧先とデータを確保できない。']),
q('q007',1,2,'store','availability','再起動可能な分析処理で一時ファイルは再生成できるが、処理結果は失いたくない。適切な保存は？',['一時ファイルはインスタンスストア、結果はS3等へ保存~再生成可能なデータと永続データを分離する。','結果もインスタンスストアだけに置く~停止や終了時に唯一の結果を失う可能性がある。','結果をRAMだけに置く~メモリは永続保存先ではない。','バックアップを取らずEC2名だけ記録する~名前から失われた結果は復元できない。']),
q('q008',1,4,'ec2','spot','チェックポイントから再開できる夜間の画像変換を安価に実行したい。どれが適する？',['Spotを使い中断時は再投入する~中断許容の処理なら余剰容量を利用できる。','必ずDedicated Hostを1台占有する~専有ホストを必要とする要件がない。','最大サイズのEC2を常時起動する~処理がない時間の固定費を増やす。','全処理をルートユーザーで動かす~権限変更は計算料金の最適化にならない。']),
q('q009',1,2,'responsibility','shared-responsibility','EC2上の自前DBをRDSに移す主な運用上の効果は？',['DB基盤の保守作業の一部をAWSへ任せられる~マネージド化で基盤管理を減らせるがデータ管理は残る。','DB内の誤データが自動的にすべて修正される~業務データの正しさは利用者が担保する。','アクセス権の設計が不要になる~認証・認可は引き続き必要。','アプリのバグがなくなる~DB基盤の運用とアプリ品質は別。']),
q('q010',1,2,'regions','az','同一リージョンに複数AZを置く価値を説明するならどれか？',['場所を分離して一部拠点の障害に備える~AZはリージョン内の独立した障害範囲として利用する。','全AZが必ず同じ建物にある~AZは独立した場所で構成される。','すべてのデータが設定なしに全AZへ複製される~複製の動作はサービスと設定による。','別AZならアプリ設計なしで無停止が保証される~負荷分散やデータ層の冗長化も必要。']),
q('q011',2,1,'role','iam-role','EC2が毎日S3へレポートを保存する。固定キーを配布せずに認可するには？',['必要なS3権限のIAMロールをEC2に関連付ける~一時認証情報を使い、キーの埋め込みを避けられる。','ルートのアクセスキーをAMIへ入れる~最上位の長期秘密情報を複製してしまう。','バケットを全世界へ書き込み公開する~認可要件を破り不正書き込みを許す。','全社員のキーを順番に使う~共有と長期認証情報管理の問題が残る。']),
q('q012',2,1,'policy','explicit-deny','同じ操作にAllowと明示的Denyが適用されている。結果は？',['拒否される~明示的DenyはAllowより優先する。','新しいポリシーが勝つ~更新日時では評価しない。','Allowが多ければ許可される~ルールの件数で判定しない。','半分のリクエストが許可される~ランダムな判定ではない。']),
q('q013',2,1,'scp','scp','OUへS3のAllowだけを記載したSCPを付けた。IAM権限がない新規ユーザーはS3を使えるか？',['SCPだけでは使えない~SCPは上限であり権限を付与しない。','自動的に全バケット管理者になる~SCPのAllowは管理権限の付与ではない。','管理アカウントにだけ新規キーが作られる~SCPは認証情報作成の仕組みではない。','S3のデータが自動公開される~公開アクセス設定を変更するものではない。']),
q('q014',2,1,'iam','least-privilege','運用者は特定バケット内のレポートを読むだけでよい。適切な権限設計は？',['対象オブジェクトの読み取りなど必要操作に絞る~作業に必要な最小範囲を許可する。','AdministratorAccessを全員へ与える~不要な管理操作まで許可する。','全サービスの書き込みを許可する~読み取り作業の要件を超える。','ルートのパスワードを共有する~個別管理と最小権限を損なう。']),
q('q015',2,1,'role','iam-role','新しいIAMロールを作成している。信頼ポリシーで決めるものは？',['そのロールを引き受けられる主体~信頼関係はAssumeRole等を行える主体を定める。','EC2のディスク容量~ストレージ設定は別。','S3の保存期間~Lifecycle等の設定。','アプリのHTTPレスポンス本文~アプリケーション処理の領域。']),
q('q016',2,1,'external','external-id','複数顧客を扱う外部監視業者へロールを委任する。顧客の取り違えを防ぐ追加条件は？',['業者が顧客ごとに管理するExternal ID~混乱した代理問題への対策として信頼ポリシーで検証する。','全顧客で同じルートキーを共有する~取り違えや漏えいの影響を増やす。','S3バケット名を短くする~代理の認可を制約しない。','MFAを全アカウントで無効化する~本人確認を弱めるだけ。']),
q('q017',2,1,'identity','identity-center','社員が複数AWSアカウントを社内IDで利用したい。中心となるサービスは？',['IAM Identity Center~従業員のアカウントアクセスをまとめて管理できる。','S3 Transfer Acceleration~ファイル転送を最適化する機能。','Amazon EFS~共有ファイルストレージ。','Amazon Route 53 Resolver~DNS名前解決のサービス。']),
q('q018',2,1,'cognito','cognito','一般顧客向けアプリにサインアップとログインを加えたい。どれを検討する？',['Amazon Cognitoユーザープール~アプリ利用者の認証を扱う。','顧客全員をAWSルートユーザーにする~アカウント管理者とアプリ顧客は別。','VPCルートテーブル~ネットワーク経路を決める機能。','EC2 Auto Scaling~計算台数を調整する機能。']),
q('q019',2,1,'sts','temporary-credentials','一時認証情報を使う利点として適切なものは？',['有効期限があり長期キーの配布を減らせる~期限付きで必要な権限を利用できる。','期限切れ後も永遠に有効~期限切れ後は新しい認証情報が必要。','すべての操作が無条件で許可される~適用される権限で制限される。','暗号化通信が不要になる~認証情報の期限と転送時保護は別。']),
q('q020',2,1,'iam','root','新規AWSアカウントのルートユーザーを保護する施策を2つ選ぶ。',['MFAを設定する~パスワードだけに依存しない本人確認を加える。','日常作業は権限を絞った別のIDで行う~ルート利用を限定し影響を抑える。','ルートキーをソース管理する~秘密情報が配布・漏えいする危険がある。','全員でパスワードを共有する~追跡と権限分離を損なう。','全バケットを公開する~ルート保護とは関係せずデータを露出する。'],[0,1]),
q('q021',2,1,'boundary','permissions-boundary','開発者がIAMロールを作成できるが、付与する権限の上限を制限したい。どれが適切か？',['アクセス許可の境界を必須にする~委任先が作る主体の最大権限を制限できる。','新規ロールに全管理権限を自動付与~権限の拡大を防げない。','S3のVersioningを無効化~IAM権限の上限に影響しない。','EC2を大型化する~認可の上限とは無関係。']),
q('q022',2,1,'abac','abac','部署が頻繁に増える。Projectタグが一致するリソースだけ操作させたい。適切な考え方は？',['ABACで主体とリソースのタグ条件を比較する~属性に基づきプロジェクト単位の認可を行える。','全員を1つの管理ユーザーに統合する~部署間の権限分離ができない。','IPアドレスだけを権限名にする~プロジェクト属性による判定にならない。','タグは料金専用なので認可に使えない~対応する条件キーでアクセス制御にも使える。']),
q('q023',2,1,'access','access-analyzer','意図しない外部アカウントへのS3共有を検出したい。適した分析機能は？',['IAM Access Analyzer~リソースポリシー等の外部アクセスを分析する。','Auto ScalingのCPU指標~処理負荷を測るもので共有権限を分析しない。','S3 Lifecycle~保存期間の管理でありアクセス分析ではない。','Route 53のレイテンシールーティング~接続先選択の機能。']),
q('q024',2,1,'s3iam','resource-policy','別アカウントへ特定S3バケットの読み取りを許可したい。リソース側で主体を指定する仕組みは？',['バケットポリシー~バケット側から対象プリンシパルへの操作許可を記載できる。','EC2起動テンプレート~インスタンスの起動設定を定義する。','VPCのCIDR~アドレス範囲でありIAMの主体指定ではない。','S3ストレージクラス~性能と保存費用の選択であり主体指定ではない。']),
q('q025',2,1,'iam','mfa','管理画面への不正ログイン対策として、パスワード漏えい時の追加防御になるものは？',['MFAを有効にする~追加要素を要求してパスワード単独の侵害を補う。','パスワードを社内wikiへ掲載する~秘密情報の漏えい範囲を拡大する。','同じパスワードを全員で使う~個別保護と追跡ができなくなる。','CloudFrontのTTLを長くする~管理者の認証強化にはならない。']),
q('q026',2,1,'scp','scp','組織のメンバーアカウントで特定操作を禁止したい。各IAM管理者がAllowしても禁止を維持するには？',['対象OUに適切なDenyのSCPを適用する~メンバーアカウントでの権限上限として働く。','全IAMユーザーへAllowを追加する~禁止とは逆の設定。','Cost Explorerの画面を隠す~API権限を制約しない。','リソース名に禁止と書く~名前は認可制御ではない。']),
q('q027',2,1,'role','cross-account','Aアカウントの担当者がBのロールを引き受けられない。確認すべき組合せは？',['A側のAssumeRole許可とB側の信頼ポリシー~呼び出す権限と受け入れる信頼関係が必要。','両アカウントのS3保存クラス~ロール引き受けの認可と無関係。','EC2のRAMとCPU~認可エラーは計算能力では解決しない。','CloudFrontのキャッシュTTLだけ~STSの権限評価に影響しない。']),
q('q028',2,1,'s3block','block-public-access','機密文書用バケットで誤ってパブリックポリシーを設定する事故を防ぎたい。どれを有効にする？',['S3 Block Public Access~パブリックアクセス設定に対する防御を加える。','S3 Transfer Acceleration~転送速度用であり公開防止ではない。','S3の静的ウェブサイト公開~公開用機能で要件と逆方向。','全ユーザー向けACL~匿名公開の原因になる。']),
q('q029',2,1,'policy','implicit-deny','同一アカウントのIAMユーザーに対象操作のAllowがなく、許可するリソースポリシーもない。結果は？',['暗黙的に拒否される~権限は既定で許可ではない。','ReadOnlyとして書き込みだけ許可~そのような既定権限はない。','利用料金を払えば自動許可~課金と認可は別。','最初の1回だけ許可~試行回数で許可は変わらない。']),
q('q030',2,1,'cognitoid','cognito-identity','モバイルアプリの認証済みユーザーへ限定したAWS一時認証情報を渡したい。どの機能か？',['Cognito IDプール~認証されたID等に応じてAWSへの一時アクセスを提供する。','ユーザープールだけで全AWS権限を自動付与~ユーザー認証とAWS認証情報の発行は区別する。','共通ルートキーをアプリに埋め込む~利用者間の分離と秘密情報の保護を失う。','Route 53パブリックホストゾーン~DNSであり認証情報を発行しない。']),
q('q031',3,2,'route','subnet','AZ-AとAZ-BへEC2を分散したい。サブネット構成は？',['各AZにそれぞれサブネットを作る~サブネットは1つのAZに属する。','1つのサブネットを2つのAZへ広げる~サブネットはAZをまたがない。','VPCを必ず別リージョンへ移す~同一リージョンでAZ分散できる。','S3バケットを2個作ればよい~EC2の配置先サブネットにはならない。']),
q('q032',3,1,'route','public-subnet','IGWへのルートがあるサブネットのEC2へIPv4で直接接続できない。SG等が正しい場合、確認する項目は？',['EC2にパブリックIPv4があるか~プライベートIPv4だけではIGWから直接公開できない。','EBSが暗号化されているか~通信経路のアドレス条件とは別。','S3の保存クラス~EC2の到達性に関係しない。','IAMユーザーの表示名~ネットワーク到達性の条件ではない。']),
q('q033',3,1,'nat','nat-gateway','非公開EC2が外部のIPv4更新サイトへ接続したい。外部からの新規接続は不要。適切な構成は？',['パブリックNAT GatewayとIGWを経由する~外向き接続とその応答を許し直接の新規着信を避けられる。','EC2に無条件の全ポート公開を設定~不要な外部接続を広げる。','ルートをすべて削除する~外部への更新通信もできなくなる。','NATだけ作りルートは変えない~対象サブネットからNATへ通信が向かわない。']),
q('q034',3,2,'nat','nat-gateway','AZごとのプライベートアプリが1台のゾーン型NAT Gatewayに依存する。AZ障害の影響を減らすには？',['各AZのNAT Gatewayへ同じAZの経路を向ける~別AZのNAT障害に依存しにくい構成にできる。','NATのタグだけを増やす~経路と障害範囲は変わらない。','全AZの経路を1つへさらに集約~単一の依存先が残る。','全EC2のRAMを倍増する~ネットワーク出口の障害対策にならない。']),
q('q035',3,1,'sg','security-group','アプリEC2のHTTPS受信をSGで許可した。戻り通信の扱いは？',['追跡された接続の応答は許可される~SGはステートフルに通信を追跡する。','必ず受信と同じ宛先ポートを送信許可する必要がある~SGの戻りは状態追跡される。','すべての未関連通信も許可される~接続の応答と新規通信は区別される。','ACLの設定は無視される~別の制御であるACLも通過が必要。']),
q('q036',3,1,'acl','network-acl','特定の悪意あるIPv4範囲をサブネット境界で明示的に拒否したい。利用できるものは？',['ネットワークACLの拒否ルール~ACLは許可と拒否の両方を持つ。','SGにDenyルールを追加~SGは許可ルールのみ。','EBSスナップショット~ディスクのバックアップ機能。','S3 Versioning~オブジェクト履歴でありパケット制御ではない。']),
q('q037',3,1,'acl','network-acl','ACLでHTTP受信を許可したが応答が返らない。確認すべき追加設定は？',['戻り先エフェメラルポートへの送信許可~ACLはステートレスなので戻り方向も必要。','受信ルールだけを複製する~逆方向の通過条件は変わらない。','EC2名を変更する~パケット通過条件に影響しない。','IAMのMFAを外す~ネットワークACLによる遮断は解消しない。']),
q('q038',3,1,'sg','security-group','DBの5432番ポートはアプリ層からだけ受けたい。IPの変化にも対応する設定は？',['DBのSGで送信元にアプリのSGを指定~アプリに関連付けたSGを信頼元として管理できる。','送信元0.0.0.0/0を許可~任意のIPv4からの到達を許す範囲になる。','DBのSGを空にする~必要なアプリ通信まで拒否される。','DBの名前にprivateと付ける~名前は通信制御として働かない。']),
q('q039',3,4,'endpoint','vpc-endpoint','非公開EC2から同一リージョンのS3へ大量転送している。NAT経由を減らす適切な方法は？',['S3ゲートウェイエンドポイントを利用する~対象ルートを通じてNATを使わずS3へ到達できる。','転送を一度海外リージョンへ迂回する~不要な通信と経路を増やす。','全オブジェクトを公開する~ネットワーク経路を最適化せず保護を弱める。','S3への操作権限を削除する~正常な転送自体ができなくなる。']),
q('q040',3,1,'privatelink','private-link','Secrets ManagerのAPIへプライベートIP経由で接続したい。対応する方式は？',['インターフェイスVPCエンドポイント~PrivateLinkで対応サービスのAPIへ接続できる。','S3専用ゲートウェイエンドポイント~Secrets Manager向けの経路にはならない。','Internet Gatewayだけ~プライベート接続の要件を満たさない。','S3 Object Lock~API接続方式とは無関係。']),
q('q041',3,2,'peering','peering','A-BとB-CにVPCピアリングがある。AからCへの推移的な通信は？',['そのピアリングだけではできない~VPCピアリングは推移的ルーティングを提供しない。','Bが自動的に中継する~ピアリングはルーターのような経由転送をしない。','IAM管理者ならネットワーク制約を無視できる~認可と経路は別。','同じタグなら自動接続される~タグは経路を作らない。']),
q('q042',3,3,'tgw','transit-gateway','数十のVPCとオンプレミス接続をハブ形式で管理したい。どれが適する？',['Transit Gateway~多数のネットワーク接続を集約できる。','全VPC間に手動でフルメッシュだけを作る~接続数と管理が膨らみハブ要件に合わない。','各VPCへS3バケットを作る~ネットワークハブにならない。','EC2のAMI共有~イメージ配布機能で通信を中継しない。']),
q('q043',3,1,'vpn','site-to-site-vpn','オンプレミスとVPCをインターネット上の暗号化トンネルで結びたい。適するサービスは？',['Site-to-Site VPN~IPsecトンネルで拠点間接続を提供する。','S3 Lifecycle~保管データのライフサイクル管理。','EC2 Auto Scaling~計算能力の台数調整。','Route 53のドメイン登録だけ~暗号化されたネットワーク経路を作らない。']),
q('q044',3,3,'direct','direct-connect','オンプレミスからAWSへの専用接続を求めている。どれを検討する？',['AWS Direct Connect~専用ネットワーク接続のためのサービス。','S3署名付きURL~限定オブジェクトアクセスで専用回線ではない。','IAMロール~APIの権限を与えるもので専用線ではない。','CloudTrail~API監査ログで通信路を提供しない。']),
q('q045',3,1,'egress','ipv6-egress','IPv6を持つプライベートEC2からインターネットへ接続し、外からの新規着信を防ぎたい。どれか？',['Egress-only Internet Gateway~IPv6の外向き通信に対応する。','IPv4専用の設計としてパブリックIPv4を必須にする~IPv6での要件を不要に変更している。','IGWと全受信許可を設定~外部からの新規着信を防ぐ要件に反する。','S3のアクセスログ~通信経路を制御しない。']),
q('q046',3,1,'flow','vpc-flow-logs','VPCで送信元・宛先やACCEPT/REJECTを調べたい。どのログを有効化する？',['VPC Flow Logs~ネットワークインターフェイスを通るIPトラフィックの情報を記録できる。','S3の旧バージョン~ネットワーク通信メタデータではない。','IAM認証情報レポートだけ~ユーザー認証情報の状況で通信フローではない。','RDSスナップショット~DBの復元データでパケット記録ではない。']),
q('q047',3,3,'route','longest-prefix','宛先10.1.2.3について、10.0.0.0/8と10.1.0.0/16の静的ルートがある。優先するのは？',['10.1.0.0/16~一致するプレフィックスがより具体的。','10.0.0.0/8~より広い範囲なので優先しない。','作成日時が早いほう~この条件では最長一致で決まる。','毎回ランダム~同条件のランダム経路選択ではない。']),
q('q048',3,1,'peering','cidr','VPCピアリング候補の2つのVPCが同じ10.0.0.0/16を使う。どの問題がある？',['CIDRが重複しそのままピアリングできない~接続先のアドレス範囲が重複しない設計が必要。','IP数が多いほど自動で接続できる~アドレスの数は重複を解消しない。','IAMユーザー名を変えれば解決する~アドレス重複の問題に影響しない。','S3複製を設定すれば経路ができる~オブジェクト複製とVPC接続は別。']),
q('q049',3,1,'endpoint','endpoint-policy','S3エンドポイントを作れば、IAMで禁止されたオブジェクトも読めるか？',['読めない。ネットワーク到達性と認可は別~エンドポイントはIAMの拒否を上書きしない。','同一リージョンなら必ず読める~地理的一致だけで権限は得られない。','NATがなければ全権限になる~出口の構成とIAM権限は無関係。','DNS名の末尾を変えれば読める~名前の変更で権限評価を回避できない。']),
q('q050',3,1,'ssm','session-manager','非公開EC2の管理でSSH受信ポートと踏み台を減らしたい。権限・Agent・到達性を整えた上で使う機能は？',['Systems Manager Session Manager~インバウンドSSHを開けずに管理セッションを利用できる。','SSHを全世界へ開く~受信ポートを減らす要件と逆。','公開鍵をS3で全世界に配る~管理経路を提供せず認証設計も不適切。','CloudFrontをDB前段に置く~EC2管理セッションの代替にはならない。']),
q('q051',4,3,'alb','alb','同じドメインの/apiと/imagesを別のEC2群へ送るには？',['ALBのパスベースルール~HTTPパスでターゲットグループを選べる。','NLBのURLパスルール~NLBはHTTPパスによるルーティングを行わない。','Route 53でURLパスを解釈~DNSはHTTPパスを扱わない。','S3のVersioning~リクエストの振り分け機能ではない。']),
q('q052',4,3,'nlb','nlb','UDPを使うゲームサーバーの前にロードバランサーを置きたい。どれか？',['Network Load Balancer~UDPトラフィックを扱える。','Application Load Balancer~HTTP系の負荷分散が用途。','S3ゲートウェイエンドポイント~S3向けの通信経路。','IAM Identity Center~従業員アクセス管理。']),
q('q053',4,2,'health','health-check','EC2自体は起動中だがアプリが応答しない。ASGにアプリ異常を反映して置換したい。どうする？',['ELBヘルスチェック連携を有効にする~ロードバランサーのアプリ健康状態を置換判断に利用できる。','EC2の名前を毎分変える~健康状態の監視にならない。','最大台数を0にする~サービスを継続できない。','ルートキーをEC2へ保存する~健康状態の検知とは無関係。']),
q('q054',4,3,'asg','target-tracking','平均CPU使用率を目標値付近へ保つよう台数を調整したい。どの方針か？',['ターゲット追跡スケーリング~目標指標に近づくよう容量を調整する。','毎年1回の手動増設だけ~日々の負荷変動に追従しない。','最小台数と最大台数を常に同値にする~台数の変動を制限してしまう。','IAMポリシーの文字数を増やす~負荷に応じた計算能力調整ではない。']),
q('q055',4,3,'scaling','scheduled-scaling','毎朝9時ちょうどにアクセスが集中し、起動に数分かかる。事前の準備として適切なのは？',['混雑前にスケジュールで容量を増やす~既知の時刻に先回りして台数を確保する。','9時を過ぎてから手動起動だけ~起動遅延により初期の負荷に対応できない。','ヘルスチェックを停止する~不健全なターゲットを除外できなくなる。','アプリデータをインスタンスストアだけに移す~混雑への事前容量確保にはならない。']),
q('q056',4,4,'spot','spot','中断通知に備えたバッチで計算費用を抑えたい。適切な実装は？',['作業を小分けにしチェックポイントから再試行する~Spot中断時に未完了処理をやり直せる。','処理結果を最後までメモリにだけ保持~中断で進捗を失う。','中断が絶対起きないと仮定する~Spot容量は中断されることがある。','中断時に全入力を削除する~復旧に必要なデータを失う。']),
q('q057',4,4,'savings','savings-plans','毎時一定の計算利用があり、インスタンスの種類も将来変わりうる。Compute Savings Plansの特徴は？',['一定の時間当たり利用額を約束して対象利用の割引を得る~柔軟な対象利用に割引を適用できる。','すべての利用を無料にする~支払いコミットメントと対象範囲がある。','Spot中断を無効にする~購入割引とSpot中断は別。','希望AZの空きを必ず確保する~容量確保と料金割引を混同してはいけない。']),
q('q058',4,2,'capacity','capacity-reservation','イベント当日に特定AZのEC2起動容量を確保したい。料金割引とは別に検討するものは？',['On-Demand Capacity Reservation~指定属性のオンデマンド容量を確保する。','Savings Plansだけ~料金割引であり容量確保の代わりにはならない。','S3 Intelligent-Tiering~保存費用の機能でEC2容量は確保しない。','CloudWatchのグラフ色~容量に影響しない。']),
q('q059',4,2,'store','instance-store','インスタンスストアに置いた唯一のデータを失わない設計へ変えるには？',['必要なデータをEBSやS3など永続保存先に保管する~一時ストレージのライフサイクルに依存しない。','EC2を終了せず名前だけ変える~障害や停止での消失対策にならない。','OSの壁紙にファイル名を書く~ファイル本体を保存していない。','IAMロールを管理者にする~権限はデータの永続性を変えない。']),
q('q060',4,3,'ami','ami','同じ構成のEC2を繰り返し素早く起動したい。OSと必要ソフトを事前にまとめるものは？',['AMI~インスタンスの起動元となるマシンイメージ。','VPC Flow Logs~ネットワーク通信の記録。','S3の署名付きURLだけ~EC2の起動イメージにはならない。','IAMグループ~ユーザー権限の集合でOSを含まない。']),
q('q061',4,3,'warm','warm-pool','アプリ初期化が長く、ASG増台時の準備時間を減らしたい。検討する機能は？',['ウォームプール~事前初期化したインスタンス群を保持できる。','スケールアウトを永久禁止~負荷増加へ対応できない。','EC2終了時に入力データを削除~起動時間短縮の機能ではない。','IAMアクセスキーを長くする~アプリの初期化時間を改善しない。']),
q('q062',4,3,'placement','placement-group','同一AZのHPC処理でノード間の低遅延が重要。適する配置戦略は？',['クラスタープレイスメントグループ~近接配置で密なノード間通信に向く。','必ず別大陸にノードを分散~通信遅延を増やす。','S3のGlacier Deep Archive~EC2配置の制御ではない。','IAMユーザーをノードごとに増やす~ネットワーク距離に影響しない。']),
q('q063',4,2,'alb','stateless','ALB配下のEC2が入れ替わるとログイン状態が消える。根本対策は？',['セッション状態を共有ストアへ外出しする~特定EC2のローカル状態への依存を減らす。','EC2の表示名を統一する~名前が同じでもメモリは共有されない。','異常なEC2へ常に固定する~単一障害点と継続性問題が残る。','ALBのDNS名を短くする~セッション保存とは無関係。']),
q('q064',4,3,'nlb','nlb','接続先のIPを許可リスト登録する取引先へTCPサービスを提供する。固定IPが必要なロードバランサーは？',['Network Load Balancer~AZごとの静的IPやElastic IPを利用できる。','ALBの現在のIPを永久固定値として配る~ALBのIP固定を前提にできない。','S3静的Webサイト~任意のTCPサービスを負荷分散しない。','Auto Scalingのグループ名~ネットワーク接続先ではない。']),
q('q065',4,2,'asg','auto-scaling','ASGの最大台数が2台で、すでに2台稼働している。負荷が増えても3台にならない理由は？',['最大台数の上限でスケールアウトが制限される~ポリシーは設定した容量範囲内で動く。','CPUが高いと必ず台数が減る~そのような一般規則ではない。','ALBは2台以上扱えない~ALBの一般的な制約ではない。','リージョン内のEC2は合計2台まで~そのような共通上限ではない。']),
q('q066',5,3,'s3','s3','Webアプリの画像をAPI経由で大量保存し、サーバー台数と独立させたい。適切な保存先は？',['Amazon S3~オブジェクトとして保存しHTTP APIで扱える。','EC2のRAMだけ~永続保存にならない。','単一EC2のインスタンスストアだけ~サーバーの終了に依存する。','IAMユーザーのタグ~大量の画像データ保存用ではない。']),
q('q067',5,3,'ebs','ebs','EC2上のOSが通常のブロックデバイスを必要とする。適切なのは？',['EBSボリューム~EC2に接続するブロックストレージ。','S3バケットをそのままOSディスクに指定~S3はブロックデバイスではない。','Route 53ホストゾーン~DNS情報の管理領域。','SNSトピック~通知の配信先でディスクではない。']),
q('q068',5,3,'efs','efs','複数AZのLinux Webサーバーで同じNFSファイルを共有したい。どれを選ぶ？',['Regional Amazon EFS~複数AZのクライアントで共有ファイルへアクセスできる。','各EC2に独立したローカルファイルだけ~内容は自動同期されない。','別AZのEC2へ同一EBSを通常接続~EBSはAZ境界をまたいだ通常接続ができない。','SQSキュー~ファイルシステムではない。']),
q('q069',5,3,'fsx','fsx-windows','既存WindowsアプリがSMBとActive Directory連携を必要とする。適する管理サービスは？',['FSx for Windows File Server~Windows向けSMB共有とAD統合に対応する。','EFSをSMB専用として使う~EFSはNFSベース。','DynamoDBへそのままSMB接続~SMBファイルサーバーではない。','CloudFrontのキャッシュだけ~編集可能な共有ファイルサーバーではない。']),
q('q070',5,2,'version','versioning','S3で同じキーのファイルを誤って上書きしたとき戻したい。事前に有効にする機能は？',['Versioning~旧バージョンを保持して復旧できる。','Transfer Acceleration~転送高速化で履歴保存ではない。','静的ウェブサイトホスティング~公開方法で旧版保存機能ではない。','タグを1個追加~ファイルの過去内容を保存しない。']),
q('q071',5,1,'lock','object-lock','監査記録の特定バージョンを保持期間中に削除できないWORM形式で保護したい。どれか？',['S3 Object Lock~保持設定でオブジェクトバージョンを保護する。','S3 Transfer Acceleration~転送機能で削除保護ではない。','EC2 Auto Scaling~計算台数の調整。','CloudFrontの圧縮~配信サイズを変える機能。']),
q('q072',5,1,'signed','presigned-url','非公開S3の請求書を顧客へ短時間だけダウンロード可能にしたい。どれか？',['期限の短い署名付きURL~権限を持つ発行者に基づく限定アクセスを提供できる。','バケット全体を匿名公開~他の請求書にも公開範囲が広がりうる。','ルートキーを顧客へ送る~過大な権限と秘密情報を渡してしまう。','S3の保存クラスだけ変更~アクセス期限を設定しない。']),
q('q073',5,4,'classes','intelligent-tiering','アクセス頻度を予測できない大量オブジェクトを、監視に基づいて階層移動したい。どれか？',['S3 Intelligent-Tiering~アクセスパターンに応じた階層最適化を行う。','全データを常に最速のEC2メモリへ保存~永続性と費用の要件に合わない。','毎日すべて削除~保存要件を満たさない。','IAMのMFAを追加するだけ~保存階層は変わらない。']),
q('q074',5,4,'classes','standard-ia','保存後ほとんど読まないが、読むときはミリ秒単位の取得が必要で複数AZ保護も必要。候補は？',['S3 Standard-IA~低頻度アクセスでも即時取得できる。','S3 Glacier Deep Archiveのみ~通常は復元待ちがある。','インスタンスストアの唯一のコピー~長期耐久性と複数AZ保護がない。','データを保存しない~読み出し要件を満たせない。']),
q('q075',5,4,'glacier','archive','10年保存する記録を年に一度読む。取り出しに半日以上待てる。低コスト候補は？',['S3 Glacier Deep Archive~長期保存と待ち時間を許容する復元向け。','全記録を常時起動EC2のRAMへ保持~永続性に問題があり保存目的に不適切。','高IOPS EBSのみを常時稼働~低頻度の長期保管には過剰になりやすい。','SQSに10年間保持~長期文書保存の仕組みではない。']),
q('q076',5,4,'lifecycle','lifecycle','ログを一定日数後に低頻度クラスへ移し、期限後に削除したい。運用を自動化する機能は？',['S3 Lifecycle~経過日数等に基づく移行・期限切れを設定できる。','IAMユーザーの自動生成~保存期間管理とは別。','VPCピアリング~ネットワーク接続機能。','ALBのヘルスチェック~アプリ応答確認でログの保管処理ではない。']),
q('q077',5,2,'replication','s3-replication','S3の新規オブジェクトを別リージョンにも継続的に複製したい。必要な構成は？',['両バケットのVersioningと適切なCRR設定・権限~クロスリージョンレプリケーションの要件を満たす。','送信元のバケット名だけ変える~複製処理は始まらない。','CloudFrontのキャッシュを永久保持~正式な永続複製先ではない。','IAMユーザーを同名で作るだけ~オブジェクトの複製設定にならない。']),
q('q078',5,3,'ebs','gp3','汎用SSDで容量とは独立してIOPSやスループットを調整したい。適切なEBSタイプは？',['gp3~容量と性能の設定を分けられる。','sc1だけ~低頻度のスループット志向HDD。','S3 Glacier~EBSタイプではない。','インスタンスストア~EBS性能設定の機能ではない。']),
q('q079',5,3,'ebs','provisioned-iops','EC2上の重要DBで高く安定したIOPSを明示的に用意したい。候補は？',['Provisioned IOPS SSD~IOPS要件の厳しいストレージ向け。','Cold HDDをIOPS重視で選ぶ~低頻度のスループット用途が中心。','S3の静的Webサイト~ブロックI/Oを提供しない。','Route 53~ストレージサービスではない。']),
q('q080',5,2,'snapshot','ebs-snapshot','EBSデータを別AZで復元してEC2へ接続したい。適切な手順は？',['スナップショットから対象AZに新ボリュームを作る~EBSボリュームは作成先AZで接続する。','元ボリュームを別AZへ直接通常接続する~EBS接続は同一AZが基本。','EC2のタグだけ変更する~ボリュームの配置は変わらない。','S3署名付きURLをEC2に貼る~ブロックボリュームの復元にはならない。']),
q('q081',5,3,'multipart','multipart-upload','大きな動画のアップロードで失敗箇所だけ再転送したい。どれか？',['S3マルチパートアップロード~パート単位で並列転送・再試行できる。','毎回ファイル全体を最初から転送~再試行の転送量が増える。','S3 Object Lockだけ~転送の分割機能ではない。','Route 53のTTL変更~アップロード単位を変えない。']),
q('q082',5,3,'transfer','transfer-acceleration','世界各地から遠い単一S3バケットへアップロードする速度を評価改善したい。候補は？',['S3 Transfer Accelerationを測定して比較する~エッジ経由の転送最適化を利用できるが効果を確認する。','S3 Versioningを止めれば必ず最速~履歴機能の停止は地理的経路改善ではない。','バケットを公開書き込みにする~認可を弱めても経路改善は保証されない。','IAMロールを増やすだけ~転送経路は変わらない。']),
q('q083',5,1,'s3encrypt','s3-encryption','S3の保存時暗号化を使えば、アクセス権を広くしても安全か？',['いいえ。暗号化とアクセス制御を両方設計する~正規に許可された読み取りは復号されるため権限の制限も必要。','はい。暗号化されていれば誰も読めない~許可された利用者には読み取りを提供する。','はい。公開ポリシーは自動削除される~暗号化は公開ポリシー削除機能ではない。','暗号化するとバックアップが不要~誤削除や復旧要件は残る。']),
q('q084',5,3,'s3consistency','s3-consistency','S3への新規PUTが成功した直後にGETする。整合性の説明として正しいのは？',['強い読み取り整合性により成功した書き込みを読める~S3のオブジェクト読み取りは強い整合性を提供する。','必ず数時間待つ必要がある~一般的なS3オブジェクトGETの整合性ではない。','キーを変えないと永久に読めない~成功したオブジェクトを同じキーで取得できる。','全バケットを公開する必要がある~認可された利用者は非公開でも読める。']),
q('q085',5,4,'version','noncurrent-version','Versioningを使うバケットの古い版が増え費用が上がった。適切な管理は？',['保持要件を満たす非現行版のLifecycleを設定~旧版にも保存費用がかかるため期間を定めて管理する。','現在版の削除だけで全旧版も必ず消えると考える~削除マーカーだけでは旧版は残る。','IAMのパスワードを変える~保存容量は変わらない。','S3へ上書きを増やす~さらに版を増やす可能性がある。']),
q('q086',6,2,'multi','rds-multi-az','RDS PostgreSQLでDBインスタンスのAZ障害に備え、自動切り替えを求める。どれか？',['Multi-AZ DBインスタンス配置~別AZのスタンバイで可用性を高める。','単一AZの容量だけ拡張~配置先障害への対処にならない。','毎年1回だけスナップショット~迅速な自動切り替えとは別。','アプリのCSSを変更~DBの可用性とは無関係。']),
q('q087',6,3,'replica','read-replica','RDSの読み取りが多く、多少古いデータでもよい分析SQLを分離したい。適切な方法は？',['リードレプリカへ分析の読み取りを向ける~参照負荷をプライマリから分離できる。','DBインスタンス配置のスタンバイを分析用に使う~このスタンバイは読み取りを提供しない。','プライマリの書き込みを全停止する~業務の継続要件を壊す。','SGを全公開する~処理能力を増やさず保護を弱める。']),
q('q088',6,2,'multi','rds-standby','RDS Multi-AZ DBインスタンス配置のスタンバイでSELECTを実行したい。正しい説明は？',['スタンバイは通常の読み取りには利用できない~高可用性用でありリードレプリカとは用途が異なる。','必ず読み取りエンドポイントがある~Multi-AZ DBクラスターとの混同。','全SQLがプライマリより高速~そもそも通常の読み取り先ではない。','IAM管理者なら任意のSQLを直接流せる~管理者権限で配置方式の仕様は変わらない。']),
q('q089',6,2,'backup','point-in-time-recovery','10時にテーブルを誤更新した。自動バックアップ保持期間内の9時59分へ戻したい。適切な方法は？',['PITRで指定時点の新しいDBを復元する~復元先を確認して接続先を切り替える。','リードレプリカなら必ず誤更新が伝わらない~誤更新も複製されうる。','Multi-AZのスタンバイに誤更新は絶対届かない~同期複製は業務上の誤りを区別しない。','DBの名前だけ変える~内容は戻らない。']),
q('q090',6,3,'proxy','rds-proxy','LambdaからRDSへの短命な接続が急増する。接続の再利用を管理したい。どれか？',['RDS Proxy~接続プーリングでDBへの接続負荷を抑える。','S3 Lifecycle~オブジェクト保存期間の管理。','Route 53ドメイン登録~DB接続のプールを行わない。','DBパスワードを公開~接続負荷を改善せず情報を漏らす。']),
q('q091',6,3,'key','partition-key','DynamoDBで全注文のパーティションキーを同じ固定文字列にして負荷が集中した。改善は？',['高カーディナリティでアクセスを分散するキーを設計~処理が一部のキーへ集中するのを抑える。','キーをさらに短い同じ定数にする~値の偏りは変わらない。','全検索をScanへ置き換える~読み取り範囲を増やし負荷を悪化させうる。','IAMの表示名を変更~データ分散に影響しない。']),
q('q092',6,3,'index','gsi','DynamoDBの主キーは注文ID。顧客IDでも効率よく注文を検索したい。追加候補は？',['顧客IDをキーにするGSI~異なるキーで問い合わせるアクセスパターンを提供する。','毎回全テーブルをScanする設計だけ~データ増加時に読み取り負担が大きい。','S3バケットポリシー~DynamoDBの索引を作らない。','CloudFrontのTTL~テーブルの検索キーを増やさない。']),
q('q093',6,3,'dynamo','consistency','DynamoDBで更新直後の最新値をテーブルから読みたい。どれを選ぶ？',['強い整合性の読み取り~成功済みの書き込みを反映した読み取りが必要な場合に選ぶ。','GSIの強い整合性読み取り~GSIは強い整合性をサポートしない。','結果整合性だけで常に最新を保証~一時的に古い値を返しうる。','Scanなら整合性設定に関係なく常に最新~操作の種類だけで整合性は保証されない。']),
q('q094',6,4,'ondemand','dynamodb-on-demand','DynamoDBのアクセスが不規則で事前の容量見積もりを避けたい。課金方式の候補は？',['オンデマンドキャパシティ~リクエストに応じた利用方式を選べる。','アクセスがなくても最大RCUを固定~不規則な需要で無駄が出やすい。','全データを毎分削除~容量管理の代替にならない。','IAMユーザーを増やしてRCUを確保~ユーザー数は処理容量ではない。']),
q('q095',6,4,'ttl','dynamodb-ttl','期限切れの一時レコードをDynamoDBから自動削除したい。即時削除でなくてよい。どれか？',['TTL属性を設定する~期限後に非同期で項目が削除される。','TTLで秒単位の削除時刻を厳密保証~削除には遅延があり即時保証ではない。','GSIだけ作成する~期限切れ削除の機能ではない。','テーブル名に日付を入れるだけ~レコードが自動削除されるわけではない。']),
q('q096',6,3,'dax','dax','DynamoDBで同じ項目への結果整合性読み取りが多く、キャッシュで短縮したい。どれか？',['DAX~DynamoDB向けのインメモリキャッシュを提供する。','RDS Proxy~RDS接続管理でDynamoDBキャッシュではない。','S3 Glacier~アーカイブ保存で低遅延キャッシュではない。','AWS Budgets~予算監視でデータをキャッシュしない。']),
q('q097',6,1,'transactions','dynamodb-transactions','DynamoDBの在庫更新と注文登録を全件成功または全件失敗にしたい。どれを使う？',['トランザクション書き込み~複数項目の変更を原子的に扱える。','独立したPutを成功確認なしに実行~途中失敗で部分更新が残りうる。','GSIを追加するだけ~複数操作の原子性は提供しない。','TTLで後日消すだけ~即時の整合した変更を保証しない。']),
q('q098',6,3,'cache','cache','商品一覧を繰り返しDBから読む。キャッシュ導入時に追加で設計すべきものは？',['元データ更新後の失効・有効期限~古い結果を返し続けない方針が必要。','DBの全バックアップを廃止~キャッシュはバックアップの代替ではない。','キャッシュは永久に正しいと仮定~更新との整合性問題が残る。','全書き込みを匿名化して許可~読み取り性能とは別にデータ保護を壊す。']),
q('q099',6,2,'aurora','aurora-replica','Auroraの障害時に昇格先を用意し、読み取りも分散したい。どれを追加する？',['別AZのAurora Replica~読み取りを担当し、フェイルオーバー先にもなれる。','CloudFrontだけ~DBノードの昇格先にはならない。','IAMユーザーだけ~DB計算リソースを増やさない。','DB名の別名だけ~実体のない別名は復旧先にならない。']),
q('q100',6,2,'global','global-tables','複数リージョンの利用者が近い場所でDynamoDBへ読み書きしたい。管理された複製方式は？',['DynamoDBグローバルテーブル~複数リージョンにまたがるレプリカを提供する。','通常テーブルを同名で手動作成するだけ~同名だけではデータは複製されない。','単一リージョンにGSIを作るだけ~別リージョンのレプリカにはならない。','S3 CRRをDynamoDBへ設定~S3オブジェクト向けの複製機能。']),
];
