import type {Term} from '../../types';
// Explicit concept IDs replace comparison-row IDs, which were unstable and incomplete.
const rows: [string,string,string,number][] = [
 ['organizations','AWS Organizations','AWSアカウントを組織とOUにまとめ、統制や請求管理を行う。',2],
 ['control-tower','AWS Control Tower','ランディングゾーンと複数アカウントの統制・払い出しを支援する。',2],
 ['permissions-boundary','アクセス許可の境界','IAM主体へ付与できる権限の上限。単独で権限を付与しない。',2],
 ['abac','ABAC','タグ等の属性を条件にするアクセス制御。認可用タグの変更権限も管理する。',2],
 ['resource-policy','リソースベースポリシー','S3バケット等のリソース側でPrincipalと許可・拒否を定める。',2],
 ['implicit-deny','暗黙的Deny','適用される許可がない要求を既定で拒否すること。',2],
 ['access-analyzer','IAM Access Analyzer','外部共有等のアクセス設定を分析する機能。検出後の是正は別途行う。',2],
 ['cognito-identity','Cognito IDプール','認証済みID等に応じた限定的なAWS一時認証情報を提供する。',2],
 ['block-public-access','S3 Block Public Access','S3のパブリックアクセス設定に対する防御。ネットワーク経路とは別。',2],
 ['vpc','Amazon VPC','リージョン内に作る論理的なネットワーク。アドレスと経路・通信許可を設計する。',3],
 ['subnet','サブネット','1つのAZに属するVPC内のアドレス区画。複数AZへまたがらない。',3],
 ['route','ルートテーブル','宛先範囲に応じ通信を送る経路の一覧。IAM認可を付与するものではない。',3],
 ['public-subnet','パブリックサブネット','IGWへの直接経路を持つサブネット。各EC2が自動公開される意味ではない。',3],
 ['longest-prefix','最長プレフィックス一致','宛先に一致するルートのうち、最も具体的なアドレス範囲を優先する。',3],
 ['security-group','セキュリティグループ','許可ルールを使うステートフルな通信制御。明示的Denyは設定しない。',3],
 ['network-acl','ネットワークACL','サブネット境界で許可・拒否を設定するステートレスな通信制御。',3],
 ['nat-gateway','NAT Gateway','外向き通信のアドレス変換を行うマネージド機能。配置・経路・料金を確認する。',3],
 ['vpc-endpoint','VPCエンドポイント','対応サービスへの専用経路やプライベート接続。接続とIAM認可は別。',3],
 ['private-link','AWS PrivateLink','対応サービスへプライベートIPで接続する仕組み。Gateway endpointとは異なる。',3],
 ['peering','VPCピアリング','2つのVPCの直接接続。重複CIDRや推移的ルーティングに制約がある。',3],
 ['transit-gateway','AWS Transit Gateway','複数VPCや拠点接続を集約するネットワークハブ。',3],
 ['site-to-site-vpn','Site-to-Site VPN','拠点とAWSをIPsecトンネルで接続する。帯域と冗長性も別に確認する。',3],
 ['direct-connect','AWS Direct Connect','AWSへの専用ネットワーク接続。既定では通信暗号化を行わない。',3],
 ['ipv6-egress','Egress-only Internet Gateway','IPv6の外向き通信と応答を許し、外からの新規接続を防ぐ経路。',3],
 ['vpc-flow-logs','VPC Flow Logs','IP通信の送受信先や許可・拒否などのメタデータ記録。パケット本文ではない。',3],
 ['session-manager','Session Manager','Agent・IAM・到達性を整え、受信SSHを開けず管理セッションを提供する。',3],
 ['ec2','Amazon EC2','要件に合わせてCPU・メモリ・I/O等を選ぶ仮想サーバー。ゲストOS保守は利用者が担う。',4],
 ['nlb','Network Load Balancer','TCP/UDP/TLSの負荷分散や固定IP要件で比較するロードバランサー。',4],
 ['auto-scaling','EC2 Auto Scaling','需要や健全性に応じインスタンス数を維持・調整する。下流の容量も考慮する。',4],
 ['target-tracking','ターゲット追跡スケーリング','1台当たりの負荷等が目標に近づくよう容量を調整する方式。',4],
 ['scheduled-scaling','予定スケーリング','既知の時刻の需要に合わせて事前に容量を変更する方式。',4],
 ['warm-pool','Warm Pool','初期化を済ませた待機インスタンスを用意しスケール時の準備時間を減らす。',4],
 ['ami','AMI','EC2の起動に使うマシンイメージ。全業務データの継続バックアップとは別。',4],
 ['capacity-reservation','Capacity Reservation','指定AZと属性のEC2容量を確保する。料金割引とは役割が異なる。',4],
 ['placement-group','プレイスメントグループ','低遅延や障害分離等の要件に合わせEC2の配置を制御する。',4],
 ['instance-family','インスタンスファミリー','CPU・メモリ・ストレージ等の特性に応じたEC2の分類。実測で選ぶ。',4],
 ['ebs','Amazon EBS','EC2で使う永続ブロックストレージ。性能設定とEC2側上限を確認する。',5],
 ['efs','Amazon EFS','Linux等から共有するマネージドNFSファイルストレージ。モードと到達性を設計する。',5],
 ['gp3','gp3','容量とは独立してIOPS・スループットを設定できる汎用SSDのEBSタイプ。',5],
 ['provisioned-iops','Provisioned IOPS SSD','厳しいIOPS・遅延要件で比較するEBS SSD。io2等がある。',5],
 ['storage-performance','IOPSとスループット','秒当たりの操作回数と転送量。I/Oサイズを掛けて帯域要求を計算する。',5],
 ['standard-ia','S3 Standard-IA','低頻度でも即時取得を求める保存階層。取得費と最低保存条件を含めて比較する。',5],
 ['intelligent-tiering','S3 Intelligent-Tiering','アクセス状況に応じ保存階層を自動調整する。監視費や対象条件を確認する。',5],
 ['archive','アーカイブ保存','長期低頻度の保存。選んだ階層の復元待ち時間・取得費が要件に合うか確認する。',5],
 ['versioning','S3バージョニング','オブジェクトの複数バージョンを保持する。削除後の旧版にも保存費が生じ得る。',5],
 ['noncurrent-version','S3旧バージョン','現在版でなくなったオブジェクト版。保持義務とLifecycleで管理する。',5],
 ['object-lock','S3 Object Lock','一定期間のオブジェクト版の上書き・削除からの保護を設計する機能。',5],
 ['fsx-windows','FSx for Windows File Server','SMB共有やActive Directory連携を要件とするWindowsファイルサービス。',5],
 ['ebs-snapshot','EBSスナップショット','EBSの時点バックアップ。復元後のアプリ整合性と起動確認も必要。',5],
 ['multipart-upload','マルチパートアップロード','大きいS3オブジェクトを部分に分けて送信し失敗部分を再送する方式。',5],
 ['transfer-acceleration','S3 Transfer Acceleration','遠隔からS3への転送改善の候補。実測効果と追加費用を比較する。',5],
 ['s3-consistency','S3の強い整合性','成功したPUT/DELETE後の読取りとLISTに変更を反映する性質。CDNや非同期複製は別。',5],
 ['s3-encryption','S3の保存時暗号化','SSE-S3やSSE-KMS等による保存データ保護。アクセス権限は別途制御する。',5],
 ['s3-replication','S3レプリケーション','ルールに応じたオブジェクト複製。過去分の複製や削除動作も確認する。',5],
 ['rds-multi-az','RDS Multi-AZ','複数AZでDBの可用性を設計する方式。単一スタンバイ配置とDBクラスターを区別する。',6],
 ['read-replica','リードレプリカ','読取りを分散するDBレプリカ。非同期複製では遅延を考慮する。',6],
 ['rds-standby','RDSの単一スタンバイ','Multi-AZ DBインスタンスの同期待機先。通常のSELECTには使わない。',6],
 ['dynamodb','Amazon DynamoDB','キーに基づくアクセスを中心とするマネージドNoSQL DB。キー分散と容量を設計する。',6],
 ['partition-key','パーティションキー','DynamoDBのデータ配置とアクセス分散を左右するキー。偏りによる集中に注意する。',6],
 ['gsi','グローバルセカンダリインデックス（GSI）','別のキーで問い合わせるDynamoDB索引。読取りは結果整合性。',6],
 ['consistency','読取り整合性','更新直後の値の反映条件。アクセス先ごとに強い整合性の対応を確認する。',6],
 ['dynamodb-on-demand','DynamoDBオンデマンド容量','読書き要求ベースの容量課金。事前の固定容量計画を減らす。',6],
 ['dynamodb-ttl','DynamoDB TTL','項目の期限後に非同期で削除する機能。指定秒での削除を保証しない。',6],
 ['dynamodb-transactions','DynamoDBトランザクション','複数項目の変更を全成功または全失敗として扱う。制約と容量費用も考慮する。',6],
 ['dax','DAX','DynamoDB用インメモリキャッシュ。結果整合性の繰返し読取りで比較する。',6],
 ['rds-proxy','RDS Proxy','DB接続をプールし再利用するサービス。SQL結果キャッシュとは別。',6],
 ['point-in-time-recovery','ポイントインタイムリカバリ（PITR）','保持期間内の指定時点へ復元する。復元先の検証と接続切替も必要。',6],
 ['aurora-replica','Aurora Replica','Auroraの読取り分散やフェイルオーバーの昇格先として使うレプリカ。',6],
 ['global-tables','DynamoDBグローバルテーブル','複数リージョンのレプリカで読み書きする構成。MREC/MRSC等の条件を確認する。',6],
 ['database-selection','データモデルによるDB選定','SQL・キーアクセス・整合性・負荷等の必須条件からDBを比較する。',6],
 ['database-cost','DBの総費用','実行・保存・I/O・レプリカ・バックアップ・転送等を合わせた費用。',6],
 ['network-cost','ネットワークの総費用','出口の稼働時間・処理量・転送経路等を同じ可用性条件で比較する費用。',3],
 ['storage-cost','ストレージの総費用','保存単価だけでなく取得・要求・移行・最低期間・旧版等を含む費用。',5],
];
export const explicitTerms: Term[] = rows.map(([id,name,meaning,ch])=>({id,name,meaning,chapterId:`ch${String(ch).padStart(2,'0')}`}));
