import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { preview } from 'vite';
await mkdir('artifacts', { recursive: true });
const server = process.env.APP_URL ? null : await preview({ preview: { host: '127.0.0.1', port: 4175, strictPort: true } });
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
const context = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true, acceptDownloads: true });
const page = await context.newPage();
const errors = [];
page.on('pageerror', e => errors.push(e.message));
page.on('requestfailed', req => console.log('FAILED', req.url(), req.failure()));
page.on('console', m => { if(m.type()==='error') console.log('CONSOLE',m.text()); });
const base = process.env.APP_URL || 'http://127.0.0.1:4175/';
const nav = name => page.getByRole('navigation', { name: 'メインナビゲーション' }).getByRole('button', { name, exact: true }).click();
async function readState() { return page.evaluate(() => new Promise((resolve, reject) => { const r = indexedDB.open('saa-learning', 1); r.onsuccess = () => { const db=r.result; const t=db.transaction('state');const g=t.objectStore('state').get('progress');g.onsuccess=()=>resolve(g.result);t.oncomplete=()=>db.close(); };r.onerror=()=>reject(r.error); })); }
try {
  await page.goto(base);
  await page.getByRole('heading', { name: '今日の一歩が、' , exact: false }).waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'mobile overflow');
  await page.screenshot({ path: 'artifacts/home-mobile.png', fullPage: true });
  await page.getByRole('button', { name: '今日のテキストを読む', exact: false }).click();
  await page.getByRole('button', { name: '読了にする', exact: true }).click();
  await page.getByRole('button', { name: '☆ ブックマーク', exact: true }).click();
  await nav('設定');
  await page.getByRole('button', { name: '教材を保存・オフライン状態を確認', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'オフライン準備完了' }).waitFor({ timeout: 60000 });
  console.log('SW', await page.evaluate(async()=>({controller:navigator.serviceWorker.controller?.scriptURL,cache:await Promise.all((await caches.keys()).map(async k=>[k,(await (await caches.open(k)).keys()).map(r=>r.url)]))})));
  await context.setOffline(true);
  await page.reload();
  await page.getByRole('heading', { name: '今日の一歩が、', exact: false }).waitFor();
  const p = await readState(); assert.equal(p.readLessons.length, 1); assert.equal(p.bookmarks.length, 1);
  await nav('用語');
  await page.getByRole('textbox', { name: '用語を検索' }).fill('S3');
  assert.ok(await page.locator('.term').count() > 0);
  await nav('問題集');
  await page.locator('.question-link').first().click();
  await page.locator('.choice').first().click();
  await page.getByRole('checkbox', { name: '自信なし・後で復習したい' }).check();
  await page.getByRole('button', { name: '回答して解説を見る' }).click();
  await page.getByRole('heading', { name: '考え方', exact: true }).waitFor();
  await page.screenshot({ path: 'artifacts/question-mobile.png', fullPage: true });
  await nav('設定');
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: 'バックアップを書き出す' }).click();
  const download = await downloadEvent; await download.saveAs('artifacts/backup.json');
  const before = await readState();
  await page.locator('input[type=file]').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{"version":2}') });
  await page.getByRole('status').filter({ hasText: '復元ファイルを確認できません' }).waitFor();
  assert.deepEqual(await readState(), before);
  await page.locator('input[type=file]').setInputFiles('artifacts/backup.json');
  await page.getByRole('button', { name: 'この内容で復元' }).click();
  await nav('問題集');
  await page.getByRole('button', { name: '模擬試験', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: '模擬試験 1 を開始', exact: true }).isDisabled(), false);
  assert.equal(await page.getByRole('button', { name: '模擬試験 2 を開始', exact: true }).isDisabled(), false);
  // A newly created page must also load the complete shell without a network.
  const fresh = await context.newPage(); await fresh.goto(base); await fresh.getByRole('heading', { name: '今日の一歩が、', exact: false }).waitFor(); await fresh.close();
  await context.setOffline(false);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await nav('今日'); await page.screenshot({ path: 'artifacts/home-desktop.png', fullPage: true });
  assert.deepEqual(errors, [], 'runtime errors');
  console.log('PASS: mobile layout, lesson state, service worker install, offline reload/new page, unseen content, answer/explanation, backup reject/restore, two mock exams enabled, no runtime errors.');
} catch (error) {
  console.log('PAGE:', await page.locator('body').innerText().catch(() => 'unavailable'));
  console.log('ERRORS:', errors);
  console.log('HTML:', (await page.content()).slice(0,3000));
  await page.screenshot({ path: 'artifacts/failure.png', fullPage: true }).catch(() => {});
  throw error;
} finally { await browser.close(); await new Promise(resolve => server ? server.httpServer.close(resolve) : resolve()); }
