import { mkdir, writeFile } from 'node:fs/promises';
import { chapters, questions, terms } from '../src/content';
const esc = (s: string) => s.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));
const css = `body{font-family:system-ui,sans-serif;line-height:1.9;color:#18313d;margin:1.3em auto;max-width:42em;padding:0 1em}h1,h2,h3{line-height:1.5}h1{color:#126957}h2{margin-top:2em}p{white-space:pre-line}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#eef5f2;padding:1em}li{margin:.5em 0}a{color:#146b5a;overflow-wrap:anywhere}small{color:#50616a}.eyebrow{letter-spacing:.1em;color:#527366}.chapter{break-before:page}.note{border-left:4px solid #72b79d;padding:.5em 1em;background:#f2f7f3}`;
const page = (title:string, body:string) => `<?xml version="1.0" encoding="utf-8"?><!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" lang="ja" xml:lang="ja"><head><title>${esc(title)}</title><meta charset="utf-8"/><link rel="stylesheet" type="text/css" href="style.css"/></head><body>${body}</body></html>`;
const sourceHtml = (sources:{title:string;url:string;checked:string}[]) => `<p><small>公式出典（確認日 2026-10-05）：${sources.map(s=>`<a href="${esc(s.url)}">${esc(s.title)}</a>`).join(' ／ ')}</small></p>`;
const files: {name:string;data:string}[] = [];
const sections:{id:string;title:string;body:string}[]=[];
sections.push({id:'intro',title:'はじめに',body:`<p class="eyebrow">SAAへの道 / 先行学習版</p><h1>学びを、ひとつずつ。</h1><p>AWSの全体像とIAMを学ぶ2章・6レッスン、基礎問題20問、用語21件を収録しています。1日20〜30分、理解を積み上げるための最初の教材です。</p><div class="note"><p>これはSAA全範囲の完成教材ではありません。問題は用語と概念の導入用であり、本試験と同等の難度を再現する模擬試験ではありません。</p></div><h2>使い方</h2><ol><li>テキストを読み、図と比較で違いを確認する（10分）。</li><li>問題を解き、答えを見る前に理由を考える（10分）。</li><li>解説を読み、翌日もう一度思い出す（5分）。</li></ol><p>本文・図・解説は通信なしで読めます。公式出典リンクを開く場合は通信が必要です。電子書籍版には自動採点や学習履歴はありません。</p><p>作成・確認日：2026年10月5日。独自教材であり、AWS公式認定教材・公式試験問題ではありません。</p>`});
for (const c of chapters) sections.push({id:c.id,title:c.title,body:`<h1>${esc(c.title)}</h1><p>${esc(c.intro)}</p>`+c.lessons.map(l=>`<section id="${esc(l.id)}"><h2>${esc(l.title)}</h2><h3>身近なたとえ</h3><p>${esc(l.analogy)}</p><h3>仕組み</h3><p>${esc(l.explanation)}</p><pre>${esc(l.diagram.join('\n'))}</pre><h3>選ぶポイント</h3><ul>${l.points.map(p=>`<li>${esc(p)}</li>`).join('')}</ul>${l.comparison.map(v=>`<h3>${esc(v.name)}</h3><p>${esc(v.use)}<br/>注意：${esc(v.caution)}</p>`).join('')}${sourceHtml(l.sources)}</section>`).join('')});
sections.push({id:'questions',title:'基礎問題20問',body:'<h1>基礎問題20問</h1><p>紙やメモに回答を控えてから解説を開きましょう。</p>'+questions.map((q,i)=>`<section id="${q.id}"><h2>問題${i+1}</h2><p>${esc(q.prompt)}</p><p>${q.answers.length}つ選択</p><ol type="A">${q.options.map(o=>`<li>${esc(o.text)}</li>`).join('')}</ol><p><a href="answers.xhtml#${q.id}-answer">この問題の解説へ</a></p></section>`).join('')});
sections.push({id:'answers',title:'正解と解説',body:'<h1>正解と解説</h1>'+questions.map((q,i)=>`<section id="${q.id}-answer"><h2>問題${i+1}の解説</h2><p>正解：${esc(q.answers.map(a=>a.toUpperCase()).join('・'))}</p><p>${esc(q.explanation)}</p>${q.options.map(o=>`<p><strong>${o.id.toUpperCase()} ${q.answers.includes(o.id)?'［正解］':'［誤答］'} ${esc(o.text)}</strong><br/>${esc(o.explanation)}</p>`).join('')}${sourceHtml(q.sources)}<p><a href="questions.xhtml#${q.id}">問題へ戻る</a></p></section>`).join('')});
sections.push({id:'terms',title:'用語集',body:'<h1>用語集</h1>'+terms.map(t=>`<h2>${esc(t.name)}</h2><p>${esc(t.meaning)}</p>`).join('')});
files.push({name:'mimetype',data:'application/epub+zip'});
files.push({name:'META-INF/container.xml',data:'<?xml version="1.0"?><container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container"><rootfiles><rootfile full-path="EPUB/package.opf" media-type="application/oebps-package+xml"/></rootfiles></container>'});
files.push({name:'EPUB/style.css',data:css});
files.push({name:'EPUB/nav.xhtml',data:page('目次',`<nav epub:type="toc" id="toc"><h1>目次</h1><ol>${sections.map(s=>`<li><a href="${s.id}.xhtml">${esc(s.title)}</a></li>`).join('')}</ol></nav>`)});
for (const s of sections) files.push({name:`EPUB/${s.id}.xhtml`,data:page(s.title,s.body)});
files.push({name:'EPUB/package.opf',data:`<?xml version="1.0" encoding="utf-8"?><package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="book-id" xml:lang="ja"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:identifier id="book-id">urn:uuid:612766ba-9602-4ddf-9960-202610050001</dc:identifier><dc:title>SAAへの道 — 先行学習版</dc:title><dc:language>ja</dc:language><dc:creator>SAA学習プロジェクト</dc:creator><meta property="dcterms:modified">2026-10-05T00:00:00Z</meta></metadata><manifest><item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/><item id="style" href="style.css" media-type="text/css"/>${sections.map(s=>`<item id="${s.id}" href="${s.id}.xhtml" media-type="application/xhtml+xml"/>`).join('')}</manifest><spine><itemref idref="nav"/>${sections.map(s=>`<itemref idref="${s.id}"/>`).join('')}</spine></package>`});
// ZIP store format: EPUB requires the uncompressed mimetype to be the first entry.
function crc32(b:Buffer){let c=0xffffffff;for(const x of b){c^=x;for(let j=0;j<8;j++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
const local:Buffer[]=[];const central:Buffer[]=[];let offset=0;
for(const f of files){const name=Buffer.from(f.name),data=Buffer.from(f.data),crc=crc32(data);const h=Buffer.alloc(30);h.writeUInt32LE(0x04034b50);h.writeUInt16LE(20,4);h.writeUInt16LE(0x800,6);h.writeUInt16LE(0x5d45,12);h.writeUInt32LE(crc,14);h.writeUInt32LE(data.length,18);h.writeUInt32LE(data.length,22);h.writeUInt16LE(name.length,26);local.push(h,name,data);const d=Buffer.alloc(46);d.writeUInt32LE(0x02014b50);d.writeUInt16LE(20,4);d.writeUInt16LE(20,6);d.writeUInt16LE(0x800,8);d.writeUInt16LE(0x5d45,14);d.writeUInt32LE(crc,16);d.writeUInt32LE(data.length,20);d.writeUInt32LE(data.length,24);d.writeUInt16LE(name.length,28);d.writeUInt32LE(offset,42);central.push(d,name);offset+=h.length+name.length+data.length;}
const directory=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(files.length,8);end.writeUInt16LE(files.length,10);end.writeUInt32LE(directory.length,12);end.writeUInt32LE(offset,16);
await mkdir('deliverables',{recursive:true});
await writeFile('deliverables/SAA-starter.epub',Buffer.concat([...local,directory,end]));
const html=sections.map(s=>`<section class="chapter" id="${s.id}">${s.body.replace(/href="(?:answers|questions)\.xhtml#/g,'href="#')}</section>`).join('');
await writeFile('deliverables/SAA-starter.html',`<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SAAへの道 — 先行学習版</title><style>${css}</style></head><body><nav><h2>目次</h2>${sections.map(s=>`<p><a href="#${s.id}">${esc(s.title)}</a></p>`).join('')}</nav>${html}</body></html>`);
console.log(`Exported EPUB + standalone HTML: ${chapters.length} chapters / ${questions.length} questions / ${terms.length} terms`);
